# Generated by Django 5.0.6 on 2024-06-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая задача'), ('in_progress', 'Выполняется'), ('done', 'Сделано')], default='new', max_length=20),
        ),
    ]
