# Generated by Django 5.0.6 on 2024-06-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detail_views',
            field=models.TextField(blank=True, null=True),
        ),
    ]
